use Control_Libros_VC190544
--Parte II
--a
SELECT AUTORES.Nombres, AUTORES.Apellidos, AUTORES.Nacionalidad, LIBROS.Titulo
FROM AUTORES INNER JOIN DETALLE_AUTORES_LIBROS
ON AUTORES.CodAutor=DETALLE_AUTORES_LIBROS.CodAutor
INNER JOIN	LIBROS ON LIBROS.CodLibro=DETALLE_AUTORES_LIBROS.CodLibro ORDER BY AUTORES.Nombres DESC

--b
SELECT AUTORES.Nombres, AUTORES.Apellidos, LIBROS.Titulo, EDITORIALES.Nombre
FROM AUTORES INNER JOIN DETALLE_AUTORES_LIBROS
ON AUTORES.CodAutor=DETALLE_AUTORES_LIBROS.CodAutor
INNER JOIN LIBROS ON LIBROS.CodLibro=DETALLE_AUTORES_LIBROS.CodLibro 
INNER JOIN EDITORIALES ON LIBROS.CodEditorial= EDITORIALES.CodEditorial WHERE EDITORIALES.Nombre='Omega'

--c
SELECT LIBROS.Titulo, COUNT (LIBROS.Titulo) AS	Ejemplares FROM LIBROS
INNER JOIN EJEMPLARES ON LIBROS.CodLibro=EJEMPLARES.CodLibro GROUP BY LIBROS.Titulo

--d
	SELECT LIBROS.Titulo FROM LIBROS
	INNER JOIN EJEMPLARES ON LIBROS.CodLibro=EJEMPLARES.CodLibro WHERE EJEMPLARES.Estado='Prestado'

--e
SELECT LIBROS.Titulo FROM LIBROS
WHERE LIBROS.AñoEdicion BETWEEN '2000-01-01' AND '2007-01-01'
ORDER BY LIBROS.AñoEdicion ASC

--f
SELECT EJEMPLARES.Ubicacion, COUNT (LIBROS.Titulo) AS Ejemplares FROM LIBROS
INNER JOIN EJEMPLARES ON LIBROS.CodLibro=EJEMPLARES.CodLibro WHERE EJEMPLARES.Estado='Prestado'
GROUP BY EJEMPLARES.Ubicacion